### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by hillbicks** [rickkbarbosa/covid9-monitor#1]
`Traceback (most recent call last):
  File "./covid19_status.py", line 24, in <module>
    df = pd.read_html(url, index_col=0)[0]
  File "/usr/lib/python3.8/site-packages/pandas/io/html.py", line 1085, in read_html
    return _parse(
  File "/usr/lib/python3.8/site-packages/pandas/io/html.py", line 895, in _parse
    tables = p.parse_tables()
  File "/usr/lib/python3.8/site-packages/pandas/io/html.py", line 213, in parse_tables
    tables = self._parse_tables(self._build_doc(), self.match, self.attrs)
  File "/usr/lib/python3.8/site-packages/pandas/io/html.py", line 733, in _build_doc
    raise e
  File "/usr/lib/python3.8/site-packages/pandas/io/html.py", line 714, in _build_doc
    with urlopen(self.io) as f:
  File "/usr/lib/python3.8/site-packages/pandas/io/common.py", line 141, in urlopen
    return urllib.request.urlopen(*args, **kwargs)
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
`

I guess this is caused by a missing user agent that they're blocking?

**Comment by rickkbarbosa** [comment]
Hey :)

Worldometer has blocked pandas requests.

Issue fixed  in [this](https://github.com/rickkbarbosa/covid9-monitor/commit/9866270612140f6f74901d7803c4355647807a09) commit and [this](https://github.com/rickkbarbosa/covid9-monitor/commit/181e5c3f0957151b32ad0d1ee04b58ff7bc53d07)
