### ISSUE TITLE
Stop working loading

### ISSUE THREAD

**Issue by hermanekt** [rickkbarbosa/covid9-monitor#20]
Hi from previously working fine, the counter is stop working. The page on is maybe changed.

URL i can reach https://www.worldometers.info/coronavirus/#countries

`root@server:/usr/lib/zabbix/externalscripts# ./covid19_status.py`

```
Traceback (most recent call last):
  File "./covid19_status.py", line 31, in <module>
    df = df.to_json(orient='index')
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/generic.py", line 2273, in to_json
    index=index)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/json/json.py", line 62, in to_json
    index=index).write()
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/json/json.py", line 96, in __init__
    self._format_axes()
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/json/json.py", line 147, in _format_axes
    "'{orient}'.".format(orient=self.orient))
ValueError: DataFrame index must be unique for orient='index'.
```

**Comment by williamnormandia** [comment]
Hello it seems that there was some change, my monitor also stopped working.

**Comment by rickkbarbosa** [comment]
Hi all,


Worldometers has change the table index.
Now it's fixed in [last commit](https://github.com/rickkbarbosa/covid9-monitor/commit/741a76c1714e3d4663c81fb2e487f7e93115dd3f) :) 


Cheers,

**Comment by hermanekt** [comment]
Thank you all working fine now:)
