### ISSUE TITLE
Master item stop loading data.

### ISSUE THREAD

**Issue by hermanekt** [rickkbarbosa/covid9-monitor#21]
Hi Rick,

again we have same error with source page is changed.

`root@hosting1:/usr/lib/zabbix/externalscripts# ./covid19_status.py`
Traceback (most recent call last):
  File "./covid19_status.py", line 35, in <module>
    df = pd.read_html(str(soup), index_col=1, thousands=r',', flavor="bs4")[0]
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/html.py", line 1094, in read_html
    displayed_only=displayed_only)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/html.py", line 916, in _parse
    raise_with_traceback(retained)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/html.py", line 898, in _parse
    tables = p.parse_tables()
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/html.py", line 221, in parse_tables
    tables = self._parse_tables(self._build_doc(), self.match, self.attrs)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/html.py", line 570, in _parse_tables
    .format(patt=match.pattern))
ValueError: No tables found matching pattern '.+'

**Comment by rickkbarbosa** [comment]
Issue fixed on new commit!
